In [1]:
import numpy as np

In [2]:
#Sử dụng zip - set để tạo tập hợp
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]
thu_tu = [2, 3, 4, 1]
diem_so = [10, 9, 8, 7]
anh_xa = zip(thu_tu, mon_hoc, diem_so)
tap_hop = set(anh_xa) 
print(tap_hop)

{(3, 'DSTT', 9), (1, 'LaptrinhCB', 7), (2, 'ToanCC', 10), (4, 'ToanRR', 8)}


In [4]:
list(zip(range(4), range(7, 12), reversed(range(11))))

[(0, 7, 10), (1, 8, 9), (2, 9, 8), (3, 10, 7)]

In [5]:
#linspace(đầu, cuối, số lượng pt)
vec1 = np.linspace(0, 20, 5)

In [6]:
#Tạo mảng n số 0
vec5 = np.zeros(5)
print(vec5)

[0. 0. 0. 0. 0.]


In [9]:
#Tạo vecto ảo (giá trị rỗng)
vec7 = np.empty(5)
print(vec7)

[0. 0. 0. 0. 0.]


In [ ]:
np.linalg.norm(vec7)

### Thể hiện ma trận bằng numpy

In [12]:
M1 = np.array([ [9, 12], [23,30] ])
u = np.array([ 2, 1])
tichuM1 = u.dot(M1)
print(tichuM1)

[41 54]


In [17]:
#Chuyển thành dạng ma trận
np.asmatrix(M1)

matrix([[ 9, 12],
        [23, 30]])

In [14]:
mat1 = np.zeros([5,5])
mat1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
A = np.mat(np.random.random((2,2)))
#Ma trận nghịch đảo
print(A.I)
#Ma trận chuyển vị
print(A.T)

[[ -0.9528183   56.25364885]
 [  3.94385647 -78.5069059 ]]
[[0.53386628 0.02681919]
 [0.38253866 0.0064794 ]]


In [26]:
#Ma trận tam giác dưới
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower, end = "\n\n")

#Ma trận tam giác trên
M_upper = np.triu(M)
print(M_upper, end = "\n\n")

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]



In [27]:
#Vector đường chéo
v_diag = np.diag(M)
print (v_diag, end = "\n\n")

#Chuyển vector thành ma trận đường chéo
M_diag = np.diag(v_diag)
print (M_diag, end = "\n\n")

[-1 -2 -2]

[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]



In [31]:
#Tạo ma trận đơn vị có đường chéo chính là 1, các pt còn lại là 0
I = np.identity(2)
I

array([[1., 0.],
       [0., 1.]])

### Thư viện Scipy

In [15]:
import sympy as sp
M = sp.Matrix([[1, 3], [2, 4]])
M
M.det()

-2

In [16]:
v1 = sp.Matrix([5,7])
M.dot(v1)

/usr/local/lib/python3.7/dist-packages/sympy/matrices/matrices.py:1357: SymPyDeprecationWarning: 

Dot product of non row/column vectors has been deprecated since SymPy
1.2. Use * to take matrix products instead. See
https://github.com/sympy/sympy/issues/13815 for more info.

  useinstead="* to take matrix products").warn()


[26, 38]

### Giải nghiệp phương trình tuyến tính

In [ ]:
!pip install --upgrade
!pip install sympy

In [32]:
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
sp.solve([x*x+2-6, y-1-6, x+z-1, 2*x*x-8, z*z+4-5, y-z-8], [x,y,z])

[(2, 7, -1)]

In [42]:
#A = [1,2,3]
#B = [1,2,3]
A = np.array([[1,2,3], [1,4,5]])
B = np.array([[1,2,3], [1,4,6]])

In [43]:
np.array_equiv(A,B)#so sánh cả list và array(1D,2D)

False

In [44]:
np.allclose(A, B)

False

In [46]:
A = np.matrix([[1,-1,0,0],[0,1,-1,0],[0,0,0,-1],[-1,0,0,1]])
b = np.matrix([[-160], [240], [-600], [520]])
A_nghichdao = np.linalg.inv(A)
X = A_nghichdao*b
X

matrix([[ 80.],
        [240.],
        [  0.],
        [600.]])

In [47]:
A = np.matrix([[1,-1,0,0],[0,1,-1,0],[0,0,0,-1],[-1,0,0,1]])
b = np.matrix([[-160], [240], [-600], [520]])
A_nghichdao = np.invert(A)
X = A_nghichdao*b
X

matrix([[ 400],
        [-840],
        [ 520],
        [-680]])